### ISSUE TITLE
Crop starting with a left margin.

### ISSUE THREAD

**Issue by TanvirArjel** [Chronostasys/Blazor.Cropper#11]
Crop initially starting with a left margin and can not drag the crop to that margin area.

![image](https://user-images.githubusercontent.com/14342773/127746510-ccf8aa3f-8932-4db9-929f-e333062e7823.png)

**Comment by Chronostasys** [comment]
Hi TanvirArjel, I can't reproduce this issue on my machine. Could you provide an example?

**Comment by TanvirArjel** [comment]
@Chronostasys Here is my repo. Download this and run: https://github.com/TanvirArjel/BlazorImageCropper

**Comment by Chronostasys** [comment]
@TanvirArjel I still can't reproduce this on my machine. Could you provide some information about your dotnet sdk version and operation system?  
![image](https://user-images.githubusercontent.com/49905799/127759790-3ed93a29-f276-40bf-80b8-0ca52201363f.png)

**Comment by TanvirArjel** [comment]
@Chronostasys Here is are list of my SDKs:

![Capture](https://user-images.githubusercontent.com/14342773/127759861-9e462ee4-8b9a-4095-a194-f8441477c906.PNG)

I am using Visual Studio 2022 Preview 2.1 and Windows 10 latest update.

**Comment by Chronostasys** [comment]
@TanvirArjel Failed to reproduce on my windows machine. Could you try to reproduce it on your machine and record the whole process?

**Comment by TanvirArjel** [comment]
@Chronostasys Please connect me on skype Id: TanvirArjel

**Comment by Chronostasys** [comment]
@TanvirArjel I'm afraid I can't use skype. I'm Chinese and I can't even open skype's official site. Although  my company offered me a proxy to Hong Kong, I'm still getting "connection refused" error when I tried to download it.

**Comment by TanvirArjel** [comment]
Has been fixed in 1.1.5
