### ISSUE TITLE
How to get the Height and Width of the resized crop.

### ISSUE THREAD

**Issue by TanvirArjel** [Chronostasys/Blazor.Cropper#12]
In the following image, I have resized the crop but I see, currently, there is no way to get the Height and Width of the resized crop. Please add this functionality.

![image](https://user-images.githubusercontent.com/14342773/127747405-6a3c9d66-f2b9-461f-89b4-2f1b8fad1f77.png)

**Comment by TanvirArjel** [comment]
@Chronostasys It's really good to see you are fixing the issues promptly. However, Please add the documentation on how to get the Resized Height and Width here, please. I have few more issues to submit, I am going to submit those.

**Comment by Chronostasys** [comment]
> @Chronostasys It's really good to see you are fixing the issues promptly. However, Please add the documentation on how to get the Resized Height and Width here, please. I have few more issues to submit, I am going to submit those.

@TanvirArjel   I've added an event named OnSizeChanged to achieve this functionality.  
You can find example code in Sample project
https://github.com/Chronostasys/Blazor.Cropper/blob/cd468ec0d6091a039ff8233aef6bf27a09980568/CropperSample/Pages/CropperExample.razor#L32-L35

**Comment by Chronostasys** [comment]
@TanvirArjel  And it is available in nuget package version 1.1.5
