### ISSUE TITLE
ImageCroppedResult.GetBase64Async() is misleading.

### ISSUE THREAD

**Issue by TanvirArjel** [Chronostasys/Blazor.Cropper#15]
`ImageCroppedResult.GetBase64Async()` is returning the web display image format not the pure base64 string. The following line in the `GetBase64Async()`

```C#
return $"data:{Format.DefaultMimeType};base64,{Convert.ToBase64String(buffer.Array, 0, (int)stream.Length)}";
```

should be 
```C#
return Convert.ToBase64String(buffer.Array, 0, (int)stream.Length);
```
Displaying base64 string is not the responsibility of the library, it's the responsibility of the developer as follows:

```C#
PreviewImagePath = $"data:image/png;base64,{ImageBase64String}";
```

**Comment by TanvirArjel** [comment]
I am making a pull request for this.

**Comment by Chronostasys** [comment]
> I am making a pull request for this.

Thanks
