### ISSUE TITLE
Cannot crop some images

### ISSUE THREAD

**Issue by Molinware** [Chronostasys/Blazor.Cropper#29]
I loaded the image to the cropper and it does not allow to crop.

Example of image that's not working:
![Me_Inicial](https://user-images.githubusercontent.com/10515611/136794917-25921a7a-66f0-46c1-9716-68cf41d2a6b4.png)

**Comment by Molinware** [comment]
That's really odd, I tested using the sample site and it's not working here. (Chrome version 94.0.4606.81)
![image](https://user-images.githubusercontent.com/10515611/136802715-f1c9b688-7ac2-4e75-8a1f-c12db17eb683.png)

**Comment by Chronostasys** [comment]
Hi Molinware, 
I think this issue might be related to pr #32 , could you try the latest version(1.1.8) again? Feel free to contact me if the issue exists.
