### ISSUE TITLE
Question:  Why can't I get to the left part of this image?

### ISSUE THREAD

**Issue by hounddog22030** [Chronostasys/Blazor.Cropper#41]
Been doing some more testing.

Steps To Reproduce:

1. Edit CropperExample.razor (c#), change from ... to `MaxCropedHeight="15000" MaxCropedWidth="15000"` 
2. Run Sample Project
3. Click Choose File
4. Select File created from https://digital-assets.partshub.com/DVJP/460f3c4f0aba9.jpg
5. Attempt to drag over to the leftmost part of the image (see above image file in step 4 in a separate browser tab) 

Expected Result:

Able to drag to the leftmost part of the image in order to crop it.

Observed Result:

Unable to get to appx left 20% of the image.

This is reproducible from before the PR you accepted from me (commit b112ffecc656b1c95bc36546521da7fb0617b457).

**Comment by Chronostasys** [comment]
This issue is because the cropper is initially set to the left-top part of the image. And the image above is far too wide that the whole cropper box is not visible, and the image is simply "stucked" by it.  
For this issue, you can resolve this problem by setting `OffsetX` to 1500.

**Comment by Chronostasys** [comment]
I dig deeper into this issue today, and I thought  current design is not good enough. I've got a new idea, and may resolve this issue in the next version.

**Comment by Chronostasys** [comment]
Thanks. Fixed in 1.2.4.
