### ISSUE TITLE
缺陷：使用纯C#处理模式时，背景遮罩的宽度有误

### ISSUE THREAD

**Issue by LittleFish-233** [Chronostasys/Blazor.Cropper#42]
复现步骤：
1.下载示例代码
2.勾选 Pure c# Processing
3.选择文件

![image](https://user-images.githubusercontent.com/53342258/170448252-0224cba0-478e-4c70-92a9-cde7b39a1062.png)

若不勾选，一切正常

![image](https://user-images.githubusercontent.com/53342258/170448785-53842518-b0d0-4775-81ab-8eb3075b97ea.png)

报错信息：
控制台无报错信息

**Comment by Chronostasys** [comment]
我等会看看，还有最近不要用1.2.3版本，这个版本有点问题。上回那个老哥的pr里有个bug

**Comment by Chronostasys** [comment]
搞定惹，我重新把不合理的位置改了一遍，新版本（1.2.4）应该不会有这个问题了。

**Comment by LittleFish-233** [comment]
好的，非常感谢
