### ISSUE TITLE
Error in cropping the picture

### ISSUE THREAD

**Issue by SarahFathy** [Chronostasys/Blazor.Cropper#45]
Hello,
I Have the same issue as issue #43 
I'm using the Nuget package in my application so will not be able to add the work around (mentioned in the issue discussion) myself.
so my question is: **When will the new version (1.2.6) will be released** ?

**Comment by SarahFathy** [comment]
Hi Boxiu,
Unfortunately I still have the same issue even after the upgrade to version 1.2.6
![Screenshot (241)](https://user-images.githubusercontent.com/11393699/175295365-511db226-2a17-40e7-8de1-19f77da1592e.png)

**Comment by Chronostasys** [comment]
Hi @SarahFathy , seems I've made a mistake while using preprocessor. Please try v1.2.7.  
Feel free to contact me if the issue still occurs.

**Comment by SarahFathy** [comment]
Hi @Chronostasys,
It works fine now after upgrading to v1.2.7.  Thank you so much.
Have a great day!
