### ISSUE TITLE
How to crop existing base64 image, without loading from file

### ISSUE THREAD

**Issue by linekg** [Chronostasys/Blazor.Cropper#46]
Hello, How to crop existing base64 image, without loading from file?
Can you help me

**Comment by Chronostasys** [comment]
Hi @linekg , you can create a [stream file obejct](https://github.com/Chronostasys/Blazor.Cropper/blob/master/Blazor.Cropper/StreamFile.cs) from the base64 data and set the cropper's `ImageFile` property to it.

**Comment by linekg** [comment]
Thank you @Chronostasys
