### ISSUE TITLE
Why require InputFile?

### ISSUE THREAD

**Issue by milambert6178** [Chronostasys/Blazor.Cropper#47]
Like the control, but could you update (or workaround) the requirement to have and InputFile control and use a base64/filestream as the datasource?

**Comment by Chronostasys** [comment]
> Like the control, but could you update (or workaround) the requirement to have and InputFile control and use a base64/filestream as the datasource?

Duplicate #46 .  
I'll add tutorial to doc and samples ASAIC

**Comment by Chronostasys** [comment]
Docs and sample updated

**Comment by milambert6178** [comment]
Thanks, working great.   Though the cropped image in almost 4x-6x the file size of the original iBrowserfile.   I set the ImageFile with Ibrowserfile of say 67k (small doc pics), but after I save using GetDataAsync() it's size balloons to ~500-600k.  I would think the cropped image should be even smaller.  Though, I don't really know much about image processing.  Any suggestion, resized options?  I use iBrowserFile RequestImageFileAsync() when I use InputFile control and that works great, but even when I use the resized file in Cropper the resulting image is 4-6x larger than the original.

**Comment by Chronostasys** [comment]
> Thanks, working great. Though the cropped image in almost 4x-6x the file size of the original iBrowserfile. I set the ImageFile with Ibrowserfile of say 67k (small doc pics), but after I save using GetDataAsync() it's size balloons to ~500-600k. I would think the cropped image should be even smaller. Though, I don't really know much about image processing. Any suggestion, resized options? I use iBrowserFile RequestImageFileAsync() when I use InputFile control and that works great, but even when I use the resized file in Cropper the resulting image is 4-6x larger than the original.

Yes, you are right. That's probably because I converted the cropped images to full quality pngs. Thanks for sharing, I'll try to fix it recently.

**Comment by Chronostasys** [comment]
> > Thanks, working great. Though the cropped image in almost 4x-6x the file size of the original iBrowserfile. I set the ImageFile with Ibrowserfile of say 67k (small doc pics), but after I save using GetDataAsync() it's size balloons to ~500-600k. I would think the cropped image should be even smaller. Though, I don't really know much about image processing. Any suggestion, resized options? I use iBrowserFile RequestImageFileAsync() when I use InputFile control and that works great, but even when I use the resized file in Cropper the resulting image is 4-6x larger than the original.
> 
> Yes, you are right. That's probably because I converted the cropped images to full quality pngs. Thanks for sharing, I'll try to fix it recently.

I'll open a new issue for it

**Comment by Chronostasys** [comment]
> Thanks, working great. Though the cropped image in almost 4x-6x the file size of the original iBrowserfile. I set the ImageFile with Ibrowserfile of say 67k (small doc pics), but after I save using GetDataAsync() it's size balloons to ~500-600k. I would think the cropped image should be even smaller. Though, I don't really know much about image processing. Any suggestion, resized options? I use iBrowserFile RequestImageFileAsync() when I use InputFile control and that works great, but even when I use the resized file in Cropper the resulting image is 4-6x larger than the original.

I add a `Quality` parameter in version 1.2.8 which can used to decrease out the size of jpg and webp image. And the cropper's output format will follow the input img's by default, which should significantly decrease the output image 'ssize when cropping jpg comparing to the former version

**Comment by milambert6178** [comment]
Thanks for the quick fix, though when I try to update through NuGet Package Manager I now lose the Blazor.Cropper reference.  Get a Namespace not found at Using Blazor.Cropper. Have this in my csproj file:     <PackageReference Include="Chronos.Blazor.Cropper" Version="1.2.8" />

**Comment by Chronostasys** [comment]
> Thanks for the quick fix, though when I try to update through NuGet Package Manager I now lose the Blazor.Cropper reference. Get a Namespace not found at Using Blazor.Cropper. Have this in my csproj file: PackageReference Include= "Chronos.Blazor.Cropper" Version="1.2.8"
> 
> Mike

Have you tried  `dotnet restore`? If it doesn't work, please post the error message.

**Comment by milambert6178** [comment]
> 

no change with restore..  I don't really get an error, just can't find the Blazor.Cropped Namespace.  If I go back to 1.2.7, it works but when I update to 1.2.8 it breaks.  Weird...
![image](https://user-images.githubusercontent.com/86315520/185204749-71a6ef05-00ec-408d-ad44-3220c095aaeb.png)
 Here is my csproj
![image](https://user-images.githubusercontent.com/86315520/185205352-0fa5509d-b6fc-4f14-b6ca-b48922155ba1.png)

**Comment by Chronostasys** [comment]
> > 
> 
> no change with restore.. I don't really get an error, just can't find the Blazor.Cropped Namespace. If I go back to 1.2.7, it works but when I update to 1.2.8 it breaks. Weird... ![image](https://user-images.githubusercontent.com/86315520/185204749-71a6ef05-00ec-408d-ad44-3220c095aaeb.png) Here is my csproj ![image](https://user-images.githubusercontent.com/86315520/185205352-0fa5509d-b6fc-4f14-b6ca-b48922155ba1.png)

@milambert6178 Thanks for the info. I think I found the problem: I added dotnet 6 to the target frameworks, but didn't update the dependencies. I fixed it in v 1.2.9, you may need to wait a few minutes before this version available.

**Comment by milambert6178** [comment]
> > > 
> > 
> > 
> > no change with restore.. I don't really get an error, just can't find the Blazor.Cropped Namespace. If I go back to 1.2.7, it works but when I update to 1.2.8 it breaks. Weird... ![image](https://user-images.githubusercontent.com/86315520/185204749-71a6ef05-00ec-408d-ad44-3220c095aaeb.png) Here is my csproj ![image](https://user-images.githubusercontent.com/86315520/185205352-0fa5509d-b6fc-4f14-b6ca-b48922155ba1.png)
> 
> @milambert6178 Thanks for the info. I think I found the problem: I added dotnet 6 to the target frameworks, but didn't update the dependencies. I fixed it in v 1.2.9, you may need to wait a few minutes before this version available.

**Comment by milambert6178** [comment]
> > > 
> > 
> > 
> > no change with restore.. I don't really get an error, just can't find the Blazor.Cropped Namespace. If I go back to 1.2.7, it works but when I update to 1.2.8 it breaks. Weird... ![image](https://user-images.githubusercontent.com/86315520/185204749-71a6ef05-00ec-408d-ad44-3220c095aaeb.png) Here is my csproj ![image](https://user-images.githubusercontent.com/86315520/185205352-0fa5509d-b6fc-4f14-b6ca-b48922155ba1.png)
> 
> @milambert6178 Thanks for the info. I think I found the problem: I added dotnet 6 to the target frameworks, but didn't update the dependencies. I fixed it in v 1.2.9, you may need to wait a few minutes before this version available.

Nope, same issue. It works fine when I go back to 1.2.7.

**Comment by milambert6178** [comment]
> > > > > 
> > > > 
> > > > 
> > > > no change with restore.. I don't really get an error, just can't find the Blazor.Cropped Namespace. If I go back to 1.2.7, it works but when I update to 1.2.8 it breaks. Weird... ![image](https://user-images.githubusercontent.com/86315520/185204749-71a6ef05-00ec-408d-ad44-3220c095aaeb.png) Here is my csproj ![image](https://user-images.githubusercontent.com/86315520/185205352-0fa5509d-b6fc-4f14-b6ca-b48922155ba1.png)
> > > 
> > > 
> > > @milambert6178 Thanks for the info. I think I found the problem: I added dotnet 6 to the target frameworks, but didn't update the dependencies. I fixed it in v 1.2.9, you may need to wait a few minutes before this version available.
> > 
> > 
> > Nope, same issue. It works fine when I go back to 1.2.7.
> 
> Could you try to restart the ide? The issue disappeared on my computer after update to v 1.2.9. <img alt="image" width="1066" src="https://user-images.githubusercontent.com/49905799/185219659-728a9236-c791-43af-964a-acad345feaa9.png">

Nope, same issue.  I even tried it on a completely different project and got the same result...

**Comment by Chronostasys** [comment]
> 

Could you upload a simple git project?

**Comment by Chronostasys** [comment]
Alright, I'm facing the same issue after I manually remove the nuget cache. I'll dig deeper into it

**Comment by milambert6178** [comment]
> Alright, I'm facing the same issue after I manually remove the nuget cache. I'll dig deeper into it

Ok, I just created a brand new project and got the same error too.  I'll wait to here back.  Thanks Again!

**Comment by Chronostasys** [comment]
> > Alright, I'm facing the same issue after I manually remove the nuget cache. I'll dig deeper into it
> 
> Ok, I just created a brand new project and got the same error too. I'll wait to here back. Thanks Again!

Thanks so much for your efforts. Please try v 1.2.10, it's likely a cd related issue.

**Comment by milambert6178** [comment]
> 

Yeah!  No more error!!  Thanks. So how does the Quality setting work?  Is it like 1-100, with 100 being original?

**Comment by Chronostasys** [comment]
> > 
> 
> Yeah! No more error!! Thanks. So how does the Quality setting work? Is it like 1-100, with 100 being original?

Yep, remember it only works for jpg and webp format.

**Comment by milambert6178** [comment]
> 

So the file size really doesn't change no matter what I set the Quality param to.  The original is only 67K, but after I crop it, it jumps to over 400K not matter if I set the Quality param to 1 or 100.  I'm using a very stripped-down declaration of Copper, should there be more I should be declaring?
![image](https://user-images.githubusercontent.com/86315520/185242992-ba80c1ed-65ba-4813-a81b-ac840a26f690.png)

**Comment by milambert6178** [comment]
> > 
> 
> So the file size really doesn't change no matter what I set the Quality param to. The original is only 67K, but after I crop it, it jumps to over 400K no matter if I set the Quality param to 1 or 100. I'm using a very stripped-down declaration of Copper, should there be more I should be declaring? ![image](https://user-images.githubusercontent.com/86315520/185242992-ba80c1ed-65ba-4813-a81b-ac840a26f690.png)

Ignore that, I must have done something wrong, after playing with it a bit more, things are working perfectly!  Thanks for all your help and quick response!! Appreciate it..
