### ISSUE TITLE
[QUESTION] OffsetX and OffsetY

### ISSUE THREAD

**Issue by angelru** [Chronostasys/Blazor.Cropper#60]
I can't get X, Y. I'm using as you have in your example, am I missing something?

do i have to use cropper.GetCropInfo()?

if I bind OffsetX and OffsetY to properties it is always 0

**Comment by Chronostasys** [comment]
Hi @angelru , `OffsetX` and `OffsetY` are parameters, they are used to set the initial value of the x/y. If you want to get the value of x/y during cropping, use `cropper.GetCropInfo()` instead.

**Comment by angelru** [comment]
Thanks
