### ISSUE TITLE
Error with multiple cropper element in a single page

### ISSUE THREAD

**Issue by xcodiyapa** [Chronostasys/Blazor.Cropper#70]
When I create a razor page with 2 cropper elements. It would not work. My assumption it happens due to same DOM ID in html end. Is there any way to handle it?
![image](https://github.com/Chronostasys/Blazor.Cropper/assets/139002094/13a33cef-7a60-44ca-9d37-fe80f4dca499)

**Comment by Chronostasys** [comment]
Hi @xcodiyapa , it seems like a js-interop error. Did you correctly referenced [the static js file](https://github.com/Chronostasys/Blazor.Cropper#step1-add-script-referrence)?

**Comment by xcodiyapa** [comment]
Hi @Chronostasys , Yes JS file reference is correct. Let me explain little more. The circular image and upload button is combined in a custom component named as **AppImageUpload.razor** which is added to the the main ui component. Look at the below images (part of my code block)...
![image](https://github.com/Chronostasys/Blazor.Cropper/assets/139002094/16d2a0d7-023e-401a-a99f-53b647060292)

![image](https://github.com/Chronostasys/Blazor.Cropper/assets/139002094/49f42b9e-ff65-4e84-ab11-fbac7c1d1d63)

When I add **AppImageUpload.razor** twice, this error occurs due to the html DOM id confliction (probably)

**Comment by xcodiyapa** [comment]
Hello sir, is there any updates??

**Comment by Chronostasys** [comment]
> Hello sir, is there any updates??

Apologies for the delayed response—I've been rather preoccupied with work recently. For us to best assist you, could you kindly provide a simple, reproducible example of the project? This would significantly expedite the troubleshooting process.

**Comment by xcodiyapa** [comment]
[CropperTest.zip](https://github.com/Chronostasys/Blazor.Cropper/files/12385354/CropperTest.zip)

Here is the sample...

**Comment by Chronostasys** [comment]
> [CropperTest.zip](https://github.com/Chronostasys/Blazor.Cropper/files/12385354/CropperTest.zip)
> 
> Here is the sample... Please look at counter page for positive output... And weather page for error output...
> 
> Thanks

Just found the problem. I've wrote jsinvokable methods in the component itself, which confuses the runtime when there's multiple cropper elements(as there are multiple methods with same name).

**Comment by Chronostasys** [comment]
Fixed in 1.2.15.
