### ISSUE TITLE
[Error] "setVersion" was undefined

### ISSUE THREAD

**Issue by turb0Code** [Chronostasys/Blazor.Cropper#71]
I'am facing this issue while implementing _Cropper_ component (directly from your example CropperSampleV6).  

![cropper](https://github.com/Chronostasys/Blazor.Cropper/assets/112781095/8148a744-0af2-496a-bf56-0b26fc0e4cd4)

**Comment by Chronostasys** [comment]
Hi @turb0Code , did you add the [js file reference](https://github.com/Chronostasys/Blazor.Cropper#step1-add-script-referrence) to your project correctly? The error seems to be related to js interop.
